# Generated by Django 5.2 on 2026-03-03 22:18

import django.db.models.deletion
import django_ckeditor_5.fields
import qbank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_question', models.CharField(choices=[('تستی چهارگزینه\u200cای', 'تستی چهارگزینه\u200cای'), ('درست / نادرست', 'درست / نادرست'), ('پاسخ کوتاه ', 'پاسخ کوتاه '), ('پاسخ تشریحی', 'پاسخ تشریحی'), ('مبتنی بر تصویر', 'مبتنی بر تصویر'), ('سوال از فایل PDF', 'سوال از فایل PDF')], max_length=50, verbose_name='نوع سوال')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان سوال')),
                ('lesson', models.CharField(max_length=255, verbose_name='مبحث')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='متن سوال')),
                ('image', models.ImageField(blank=True, null=True, upload_to=qbank.models.photo_path_upload_to, verbose_name='تصویر سوال')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=qbank.models.photo_path_upload_to, verbose_name='فایل PDF سوال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('has_options', models.BooleanField(default=False, verbose_name='دارای گزینه های دیگر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('solving_time', models.PositiveIntegerField(default=1, verbose_name='زمان پیشنهادی حل به دقیقه')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionLessonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('name', models.CharField(max_length=255, verbose_name='نام دسته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته ها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPossible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام سطح')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سطح',
                'verbose_name_plural': 'سطوح',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_answer', models.CharField(choices=[('پاسخ تشریحی', 'پاسخ تشریحی'), ('پاسخ تصویری', 'پاسخ تصویری'), ('پاسخ PDF', 'پاسخ PDF')], max_length=50, verbose_name='نوع پاسخ صحیح')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='متن پاسخ')),
                ('image', models.ImageField(blank=True, null=True, upload_to=qbank.models.photo_path_upload_to, verbose_name='تصویر پاسخ')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=qbank.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_key', to='qbank.questionbank', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ صحیح (ادمین)',
                'verbose_name_plural': 'پاسخ\u200cهای صحیح (ادمین)',
            },
        ),
        migrations.AddField(
            model_name='questionbank',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qbank.questionlessoncategory', verbose_name='دسته'),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='متن گزینه')),
                ('is_correct', models.BooleanField(default=False, verbose_name='گزینه صحیح')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='qbank.questionbank', verbose_name='سوال')),
            ],
            options={
                'verbose_name': ' گزینه سوال تست',
                'verbose_name_plural': 'گزینه\u200cها سوالات تستی',
                'ordering': ['-order'],
            },
        ),
        migrations.AddField(
            model_name='questionbank',
            name='possible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qbank.questionpossible', verbose_name='سطح'),
        ),
        migrations.CreateModel(
            name='QuestionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='qbank.questionbank')),
            ],
        ),
    ]
