# Generated by Django 5.2 on 2026-02-27 22:45

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_question', models.CharField(choices=[('MULTIPLE_CHOICE', 'تستی چهارگزینه\u200cای'), ('TRUE_FALSE', 'درست / نادرست'), ('SHORT_ANSWER', 'پاسخ کوتاه'), ('LONG_ANSWER', 'پاسخ تشریحی'), ('IMAGE_BASED', 'مبتنی بر تصویر'), ('PDF_BASED', 'سوال از فایل PDF')], max_length=50, verbose_name='نوع سوال')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان سوال')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='متن سوال')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions-bank/images/', verbose_name='تصویر سوال')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='questions-bank/pdfs/', verbose_name='فایل PDF سوال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_answer', models.CharField(choices=[('TEXT_BASED', 'پاسخ تشریحی'), ('IMAGE_BASED', 'پاسخ تصویری'), ('PDF_BASED', 'پاسخ PDF')], max_length=50, verbose_name='نوع پاسخ صحیح')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='متن پاسخ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='answers/qbank/admin/images/', verbose_name='تصویر پاسخ')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='answers/qbank/admin/pdfs/', verbose_name='فایل PDF پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_key', to='qbank.questionbank', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ صحیح (ادمین)',
                'verbose_name_plural': 'پاسخ\u200cهای صحیح (ادمین)',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='متن گزینه')),
                ('is_correct', models.BooleanField(default=False, verbose_name='گزینه صحیح')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='qbank.questionbank', verbose_name='سوال')),
            ],
            options={
                'verbose_name': ' گزینه سوال تست',
                'verbose_name_plural': 'گزینه\u200cها سوالات تستی',
                'ordering': ['order'],
            },
        ),
    ]
