# Generated by Django 5.2 on 2026-03-02 19:32

import django.db.models.deletion
import qbank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLessonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('name', models.CharField(max_length=255, verbose_name='نام دسته')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته ها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPossible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام سطح')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'سطح',
                'verbose_name_plural': 'سطوح',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=qbank.models.photo_path_upload_to, verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=qbank.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=qbank.models.photo_path_upload_to, verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=qbank.models.photo_path_upload_to, verbose_name='فایل PDF سوال'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qbank.questionlessoncategory', verbose_name='دسته'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='possible',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qbank.questionpossible', verbose_name='سطح'),
            preserve_default=False,
        ),
    ]
