# Generated by Django 5.2 on 2026-03-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='type_of_question',
            field=models.CharField(choices=[('همه', 'همه'), ('تستی چهارگزینه\u200cای', 'تستی چهارگزینه\u200cای'), ('درست / نادرست', 'درست / نادرست'), ('پاسخ کوتاه ', 'پاسخ کوتاه '), ('پاسخ تشریحی', 'پاسخ تشریحی'), ('مبتنی بر تصویر', 'مبتنی بر تصویر'), ('سوال از فایل PDF', 'سوال از فایل PDF')], max_length=50, verbose_name='نوع سوال'),
        ),
    ]
