# Generated by Django 5.2 on 2026-03-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0002_questionlessoncategory_questionpossible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='solving_time',
            field=models.PositiveIntegerField(default=1, verbose_name='زمان پیشنهادی حل به دقیقه'),
        ),
        migrations.AddField(
            model_name='questionlessoncategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='questionpossible',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
