# Generated by Django 5.2 on 2026-03-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0002_alter_questionbank_type_of_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionanswerkey',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questionview',
            options={'verbose_name': 'بازدید سوال', 'verbose_name_plural': 'بازدید های سوالات'},
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='عنوان سوال'),
        ),
    ]
