# Generated by Django 5.2 on 2026-03-02 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0003_questionbank_solving_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='type_of_question',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'تستی چهارگزینه\u200cای'), ('TRUE_FALSE', 'درست / نادرست'), ('SHORT_ANSWER', 'پاسخ کوتاه '), ('LONG_ANSWER', 'پاسخ تشریحی'), ('IMAGE_BASED', 'مبتنی بر تصویر'), ('PDF_BASED', 'سوال از فایل PDF')], max_length=50, verbose_name='نوع سوال'),
        ),
        migrations.CreateModel(
            name='QuestionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='qbank.questionbank')),
            ],
        ),
    ]
