# Generated by Django 5.2 on 2026-03-25 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0003_alter_questionanswerkey_options_and_more'),
        ('quiz', '0038_alter_question_image_alter_question_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.lessioncategories', verbose_name='درس'),
        ),
    ]
