# Generated by Django 5.2 on 2026-03-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0004_alter_questionbank_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionanswerkey',
            options={'verbose_name': 'کلید سوال', 'verbose_name_plural': 'کلید های  سوال'},
        ),
        migrations.AlterModelOptions(
            name='questionbank',
            options={'ordering': ['-order', '-id'], 'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AlterModelOptions(
            name='questionpossible',
            options={'ordering': ['-order'], 'verbose_name': 'سطح', 'verbose_name_plural': 'سطوح'},
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='name',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='عنوان سوال'),
        ),
    ]
