# Generated by Django 5.2 on 2026-03-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0004_alter_questionbank_type_of_question_questionview'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='has_options',
            field=models.BooleanField(default=False, verbose_name='دارای گزینه های دیگر'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='type_of_question',
            field=models.CharField(choices=[('تستی چهارگزینه\u200cای', 'تستی چهارگزینه\u200cای'), ('درست / نادرست', 'درست / نادرست'), ('پاسخ کوتاه ', 'پاسخ کوتاه '), ('پاسخ تشریحی', 'پاسخ تشریحی'), ('مبتنی بر تصویر', 'مبتنی بر تصویر'), ('سوال از فایل PDF', 'سوال از فایل PDF')], max_length=50, verbose_name='نوع سوال'),
        ),
    ]
