# Generated by Django 5.2 on 2026-03-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0005_questionbank_has_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionbank',
            options={'ordering': ['-order'], 'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['-order'], 'verbose_name': ' گزینه سوال تست', 'verbose_name_plural': 'گزینه\u200cها سوالات تستی'},
        ),
        migrations.RenameField(
            model_name='questionview',
            old_name='blog',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='type_of_answer',
            field=models.CharField(choices=[('پاسخ تشریحی', 'پاسخ تشریحی'), ('پاسخ تصویری', 'پاسخ تصویری'), ('پاسخ PDF', 'پاسخ PDF')], max_length=50, verbose_name='نوع پاسخ صحیح'),
        ),
    ]
