# Generated by Django 5.2 on 2026-04-02 19:46

import config.storage
import qbank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0005_alter_questionanswerkey_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.storage.PublicMediaStorage, upload_to=qbank.models.photo_path_upload_to, verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=config.storage.PublicMediaStorage, upload_to=qbank.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.storage.PublicMediaStorage, upload_to=qbank.models.photo_path_upload_to, verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=config.storage.PublicMediaStorage, upload_to=qbank.models.photo_path_upload_to, verbose_name='فایل PDF سوال'),
        ),
    ]
