# Generated by Django 5.2 on 2026-03-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0006_alter_questionbank_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='lesson',
            field=models.CharField(default=1, max_length=255, verbose_name='مبحث'),
            preserve_default=False,
        ),
    ]
