# Generated by Django 5.2 on 2026-03-17 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0034_alter_question_image_alter_question_pdf_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SanatoriumWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
                ('status', models.CharField(choices=[('جاری', 'جاری'), ('تصفیه شده', 'تصفیه شده')], default='جاری', verbose_name='وضعیت')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='quiz.quiz', verbose_name='ازمون')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول ها',
            },
        ),
        migrations.CreateModel(
            name='WalletDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='quiz.studentanswer', verbose_name='پاسخ نامه')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='sanatorium.sanatoriumwallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'جزییات کیف پول',
                'verbose_name_plural': 'جزییات کیف پول',
            },
        ),
    ]
