# Generated by Django 5.2 on 2026-03-18 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanatoriumwallet',
            options={'ordering': ['-pk'], 'verbose_name': 'کیف پول', 'verbose_name_plural': 'کیف پول ها'},
        ),
        migrations.AlterModelOptions(
            name='walletdetails',
            options={'ordering': ['-pk'], 'verbose_name': 'جزییات کیف پول', 'verbose_name_plural': 'جزییات کیف پول'},
        ),
    ]
