# Generated by Django 5.2 on 2026-03-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0002_alter_sanatoriumwallet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanatoriumwallet',
            name='final_price',
            field=models.PositiveBigIntegerField(db_index=True, default=0, verbose_name='قیمت'),
        ),
    ]
