# Generated by Django 5.2 on 2026-03-29 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0040_alter_question_image_alter_question_pdf_file_and_more'),
        ('sanatorium', '0003_alter_sanatoriumwallet_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanatoriumwallet',
            name='status',
            field=models.CharField(choices=[('جاری', 'جاری'), ('درخواست تصفیه', 'درخواست تصفیه'), ('تصفیه شده', 'تصفیه شده')], default='جاری', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='walletdetails',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet', to='quiz.studentanswer', verbose_name='پاسخ نامه'),
        ),
    ]
