# Generated by Django 5.2 on 2026-03-03 22:18

import django_ckeditor_5.fields
import easy_thumbnails.fields
import phonenumber_field.modelfields
import sitesetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره')),
                ('message', models.TextField(verbose_name='پیام')),
                ('admin_read', models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره')),
            ],
            options={
                'verbose_name': 'پیام نامه',
                'verbose_name_plural': 'پیام نامه ها',
            },
        ),
        migrations.CreateModel(
            name='QuestionAndAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='جواب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال یا غیر فعال')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('addr', models.CharField(max_length=255, verbose_name='ادرس')),
                ('work_hour', models.CharField(max_length=255, verbose_name='ساعات کاری')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('short_description', models.CharField(max_length=255, verbose_name='توضیحات کوتاه')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات ')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('active_user', models.CharField(max_length=255, verbose_name='کاربر فعال')),
                ('number_questions', models.CharField(max_length=255, verbose_name='تعداد سوالات')),
                ('taken_exams', models.CharField(max_length=255, verbose_name='ازمون های برگذاری شده')),
                ('user_happies', models.CharField(max_length=255, verbose_name='رضایت کاربران')),
                ('force_to_login_with_otp', models.BooleanField(default=True, verbose_name='اجبار برای ورود با رمز یک بار مصرف')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='SiteLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام قانون')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات ')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('sort_number', models.IntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'قانون',
                'verbose_name_plural': 'قوانین',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('work', models.CharField(max_length=255, verbose_name='سمت')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره')),
                ('avatar', easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('sort_number', models.IntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
                'ordering': ['-sort_number'],
            },
        ),
    ]
