# Generated by Django 5.2 on 2026-03-02 00:33

import easy_thumbnails.fields
import sitesetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0002_site_team_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitelaw',
            options={'ordering': ['-sort_number'], 'verbose_name': 'قانون', 'verbose_name_plural': 'قوانین'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-sort_number'], 'verbose_name': 'عضو تیم', 'verbose_name_plural': 'اعضای تیم'},
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='email',
        ),
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
    ]
