# Generated by Django 5.2 on 2026-03-05 00:20

import easy_thumbnails.fields
import sitesetting.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0007_alter_team_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
    ]
