# Generated by Django 5.2 on 2026-03-08 11:44

import django.db.models.deletion
import django_ckeditor_5.fields
import easy_thumbnails.fields
import sitesetting.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0013_alter_team_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketProblemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('name', models.CharField(max_length=255, verbose_name='نام  ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته بندی مشکل تیکت',
                'verbose_name_plural': 'دسته بندی مشکلات تیکت ها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TicketProblemPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('name', models.CharField(max_length=255, verbose_name='بخش مرتبط')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'بخش مرتبط مشکلات در تیکت',
                'verbose_name_plural': 'بخش های مرتبط مشکلات در تیکت',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='موضوع')),
                ('description', models.TextField(verbose_name='توضیحات ')),
                ('file', models.FileField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='پیوست')),
                ('priority', models.CharField(choices=[('پایین', 'پایین'), ('متوسط', 'متوسط'), ('بالا', 'بالا'), ('فوری', 'فوری')], max_length=255, verbose_name='اهمیت')),
                ('status', models.CharField(choices=[('کنسل شده', 'کنسل شده'), ('حل شده', 'حل شده'), ('در انتطار پاسخ ادمین', 'در انتطار پاسخ ادمین'), ('در انتطار پاسخ کاربر', 'در انتطار کاربر')], max_length=255, verbose_name='وضعیت')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال درخواست')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_admin', to=settings.AUTH_USER_MODEL, verbose_name='ادمین')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='درخواست دهنده')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='sitesetting.ticketproblemcategory', verbose_name='دسته بندی مشکلات تیکت ها')),
                ('placement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='sitesetting.ticketproblemplacement', verbose_name='بخش های مرتبط مشکلات در تیکت')),
            ],
            options={
                'verbose_name': 'تیکت ',
                'verbose_name_plural': 'تیکت  ها',
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال پیام')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین')),
                ('is_read_by_user', models.BooleanField(default=False, verbose_name='خوانده شده توسط کاربر')),
                ('is_admin_message', models.BooleanField(default=False, verbose_name='پیام ادمین')),
                ('admin_message', django_ckeditor_5.fields.CKEditor5Field(verbose_name='پیام')),
                ('user_message', models.TextField(verbose_name='پیام')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='sitesetting.ticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پیام تیکت  ',
                'verbose_name_plural': 'پیام های تیکت',
            },
        ),
    ]
