# Generated by Django 5.2 on 2026-03-08 12:37

import django_ckeditor_5.fields
import easy_thumbnails.fields
import sitesetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0014_ticketproblemcategory_ticketproblemplacement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-id'], 'verbose_name': 'تیکت ', 'verbose_name_plural': 'تیکت  ها'},
        ),
        migrations.AlterModelOptions(
            name='ticketchat',
            options={'ordering': ['-id'], 'verbose_name': 'پیام تیکت  ', 'verbose_name_plural': 'پیام های تیکت'},
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=sitesetting.models.photo_path_upload_to, verbose_name='پیوست'),
        ),
        migrations.AlterField(
            model_name='ticketchat',
            name='admin_message',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='ticketchat',
            name='user_message',
            field=models.TextField(blank=True, null=True, verbose_name='پیام'),
        ),
    ]
