# Generated by Django 5.2 on 2026-03-08 13:15

import django.db.models.deletion
import easy_thumbnails.fields
import sitesetting.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0015_alter_ticket_options_alter_ticketchat_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionandanswer',
            options={'ordering': ['order'], 'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AddField(
            model_name='questionandanswer',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتیب (توجه داشته باشید ۳ اول ترتیب در صفحه تیکت ها نمایش داده خواهد شد)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_admin', to=settings.AUTH_USER_MODEL, verbose_name='ادمین'),
        ),
    ]
