# Generated by Django 5.2 on 2026-03-08 13:36

import easy_thumbnails.fields
import sitesetting.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0016_alter_questionandanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
    ]
