# Generated by Django 5.2 on 2026-03-08 19:52

import easy_thumbnails.fields
import sitesetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0017_alter_site_logo_alter_team_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketchat',
            options={'ordering': ['id'], 'verbose_name': 'پیام تیکت  ', 'verbose_name_plural': 'پیام های تیکت'},
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('کنسل شده', 'کنسل شده'), ('حل شده', 'حل شده'), ('در انتظار پاسخ ادمین', 'در انتظار پاسخ ادمین'), ('در انتظار پاسخ کاربر', 'در انتظار کاربر')], max_length=255, verbose_name='وضعیت'),
        ),
    ]
