# Generated by Django 5.2 on 2026-03-10 16:53

import django.utils.timezone
import easy_thumbnails.fields
import sitesetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0025_alter_site_logo_alter_team_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='copyright',
            field=models.CharField(default='© 1405 سورنا . تمام حقوق محفوظ است.', max_length=255, verbose_name='متن کپی رایت'),
        ),
        migrations.AddField(
            model_name='site',
            name='eitaa_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='لینک حساب ایتا'),
        ),
        migrations.AddField(
            model_name='site',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='لینک حساب اینستاگرام'),
        ),
        migrations.AddField(
            model_name='site',
            name='tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='تگ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='لینک حساب تلگرام'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
    ]
