# Generated by Django 5.2 on 2026-03-19 21:01

import easy_thumbnails.fields
import sitesetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0034_alter_site_logo_alter_team_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionandanswer',
            name='order',
            field=models.PositiveIntegerField(db_index=True, verbose_name='ترتیب (توجه داشته باشید ۳ اول ترتیب در صفحه تیکت ها نمایش داده خواهد شد)'),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='question',
            field=models.TextField(db_index=True, verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='موضوع'),
        ),
    ]
