# Generated by Django 5.2 on 2026-03-27 19:18

import easy_thumbnails.fields
import sitesetting.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0037_alter_site_logo_alter_team_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketproblemcategory',
            options={'ordering': ['-order'], 'verbose_name': 'دسته بندی مشکل تیکت', 'verbose_name_plural': 'دسته بندی مشکلات تیکت ها'},
        ),
        migrations.AlterModelOptions(
            name='ticketproblemplacement',
            options={'ordering': ['-order'], 'verbose_name': 'بخش مرتبط مشکلات در تیکت', 'verbose_name_plural': 'بخش های مرتبط مشکلات در تیکت'},
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
    ]
