# Generated by Django 5.2 on 2026-04-01 16:24

import easy_thumbnails.fields
import sitesetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0040_alter_site_logo_alter_team_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='active_blog',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='site',
            name='active_qbank',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
    ]
