# Generated by Django 5.2 on 2026-04-02 19:46

import easy_thumbnails.fields
import sitesetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0041_site_active_blog_site_active_qbank_alter_site_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='active_blog',
            field=models.BooleanField(default=True, verbose_name='فعال بودن قسمت بلاگ '),
        ),
        migrations.AlterField(
            model_name='site',
            name='active_qbank',
            field=models.BooleanField(default=True, verbose_name='فعال بودن قسمت بانک سوالات'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
    ]
