# Generated by Django 5.2 on 2026-04-03 15:00

import config.storage
import easy_thumbnails.fields
import sitesetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0042_alter_site_active_blog_alter_site_active_qbank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(storage=config.storage.PublicMediaStorage, upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(storage=config.storage.PublicMediaStorage, upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, null=True, storage=config.storage.PublicMediaStorage, upload_to=sitesetting.models.photo_path_upload_to, verbose_name='پیوست'),
        ),
    ]
