# Generated by Django 5.2 on 2026-04-03 19:46

import config.storage
import easy_thumbnails.fields
import sitesetting.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0043_alter_site_logo_alter_team_avatar_alter_ticket_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(storage=config.storage.PublicMediaStorage, upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(storage=config.storage.PublicMediaStorage, upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
    ]
