# Generated by Django 5.2 on 2026-04-06 23:08

import config.storage
import easy_thumbnails.fields
import sitesetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0045_alter_site_logo_alter_team_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='active_forgot_password',
            field=models.BooleanField(default=True, verbose_name='فعال کردن ورود با رمز عبور'),
        ),
        migrations.AddField(
            model_name='site',
            name='active_login_otp',
            field=models.BooleanField(default=True, verbose_name='فعال کردن ورود با otp'),
        ),
        migrations.AddField(
            model_name='site',
            name='active_login_password',
            field=models.BooleanField(default=True, verbose_name='فعال کردن ورود با رمز عبور'),
        ),
        migrations.AddField(
            model_name='site',
            name='force_to_message_verify',
            field=models.BooleanField(default=True, verbose_name='اجبار برای تاییده otp'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(storage=config.storage.LogoStorage, upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(storage=config.storage.PublicMediaStorage, upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
    ]
