# Generated by Django 5.2 on 2026-04-06 23:12

import config.storage
import easy_thumbnails.fields
import sitesetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0046_site_active_forgot_password_site_active_login_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='active_registering',
            field=models.BooleanField(default=True, verbose_name='فعال کردن ثبت نام '),
        ),
        migrations.AlterField(
            model_name='site',
            name='active_forgot_password',
            field=models.BooleanField(default=True, verbose_name='فعال کردن فراموشی رمز عبور'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(storage=config.storage.LogoStorage, upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(storage=config.storage.PublicMediaStorage, upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
    ]
