# Generated by Django 5.2 on 2026-04-06 23:17

import config.storage
import easy_thumbnails.fields
import sitesetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0047_site_active_registering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='message_danger',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پیام قرمز'),
        ),
        migrations.AddField(
            model_name='site',
            name='message_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پیام ابی'),
        ),
        migrations.AddField(
            model_name='site',
            name='message_success',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پیام سبز'),
        ),
        migrations.AddField(
            model_name='site',
            name='message_warning',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پیام زرد'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(storage=config.storage.LogoStorage, upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(storage=config.storage.PublicMediaStorage, upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
    ]
