# Generated by Django 5.2 on 2026-04-07 23:22

import config.storage
import easy_thumbnails.fields
import sitesetting.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0048_site_message_danger_site_message_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(storage=config.storage.LogoStorage, upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(storage=config.storage.PublicMediaStorage, upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس'),
        ),
    ]
