# Generated by Django 5.2 on 2026-03-03 22:18

import django.db.models.deletion
import django_ckeditor_5.fields
import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessionCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('name', models.CharField(max_length=255, verbose_name='نام درس ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'درس ',
                'verbose_name_plural': 'دروس',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MajorCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('name', models.CharField(max_length=255, verbose_name='نام رشته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'رشته ',
                'verbose_name_plural': 'رشته ها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_question', models.CharField(choices=[('تستی چهارگزینه\u200cای', 'تستی چهارگزینه\u200cای'), ('درست / نادرست', 'درست / نادرست'), ('پاسخ کوتاه', 'پاسخ کوتاه'), ('پاسخ تشریحی', 'پاسخ تشریحی'), ('مبتنی بر تصویر', 'مبتنی بر تصویر'), ('سوال از فایل PDF', 'سوال از فایل PDF')], max_length=50, verbose_name='نوع سوال')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان سوال')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='متن سوال')),
                ('image', models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر سوال')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF سوال')),
                ('score', models.PositiveIntegerField(default=1, verbose_name='نمره سوال')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان')),
                ('section', models.CharField(max_length=255, verbose_name='مبحث')),
                ('province', models.CharField(max_length=255, verbose_name=' نام استان محل برگذاری')),
                ('city', models.CharField(max_length=255, verbose_name='نام شهر محل برگذاری')),
                ('type_of_quiz', models.CharField(max_length=255, verbose_name='محل و نحوه برگذاری')),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='هزینه')),
                ('time_minutes', models.PositiveIntegerField(default=0, verbose_name='(دقیقه) تایمر')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('start_at', models.DateTimeField(verbose_name='زمان برگذاری')),
                ('stop_at', models.DateTimeField(verbose_name='زمان پایان')),
                ('last_enter', models.DateTimeField(verbose_name='اخرین زمان ورود')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='حداکثر نمره')),
                ('score', models.PositiveSmallIntegerField(default=1, verbose_name='ضریب')),
                ('capacity', models.PositiveSmallIntegerField(default=1, verbose_name='ظرفیت')),
                ('filled_capacity', models.PositiveSmallIntegerField(default=1, verbose_name=' ظرفیت پر شده')),
                ('status', models.CharField(choices=[('غیرفعال', 'غیرفعال'), ('کنسل شده', 'کنسل شده'), ('در انتظار شروع', 'در انتظار شروع'), ('شروع شده', 'شروع شده'), ('در انتظار پایان', 'در انتظار پایان'), ('پایان یافته', 'پایان یافته'), ('در انتظار تصحیح', 'در انتظار تصحیح'), ('تصحیح شده', 'تصحیح شده'), ('اعلام نتایج', 'اعلام نتایج')], default='در انتظار شروع', max_length=55, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'ازمون',
                'verbose_name_plural': 'ازمون ها',
            },
        ),
        migrations.CreateModel(
            name='QuizView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بازدید',
                'verbose_name_plural': 'بازدید ها ',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_answer', models.CharField(choices=[('پاسخ متنی', 'پاسخ متنی'), ('پاسخ تصویری', 'پاسخ تصویری'), ('پاسخ PDF', 'پاسخ PDF'), ('انتخاب گزینه', 'انتخاب گزینه')], max_length=50, verbose_name='نوع پاسخ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='متن پاسخ')),
                ('image', models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر پاسخ')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ')),
                ('score', models.FloatField(default=0, verbose_name='نمره داده شده')),
                ('is_correct', models.BooleanField(default=False, verbose_name='صحیح است؟')),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پاسخ دانش\u200cآموز',
                'verbose_name_plural': 'پاسخ\u200cهای دانش\u200cآموزان',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_answer', models.CharField(choices=[('پاسخ تشریحی', 'پاسخ تشریحی'), ('پاسخ تصویری', 'پاسخ تصویری'), ('پاسخ PDF', 'پاسخ PDF')], max_length=50, verbose_name='نوع پاسخ صحیح')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='متن پاسخ')),
                ('image', models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر پاسخ')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_key', to='quiz.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ صحیح (ادمین)',
                'verbose_name_plural': 'پاسخ\u200cهای صحیح (ادمین)',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='متن گزینه')),
                ('is_correct', models.BooleanField(default=False, verbose_name='گزینه صحیح')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': ' گزینه سوال تست',
                'verbose_name_plural': 'گزینه\u200cها سوالات تستی',
                'ordering': ['order'],
            },
        ),
    ]
