# Generated by Django 5.2 on 2026-03-03 22:34

import django.db.models.deletion
import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz', to='user.majorcategories', verbose_name='رشته تحصیلی'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='انلاین'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ'),
        ),
        migrations.DeleteModel(
            name='MajorCategories',
        ),
    ]
