# Generated by Django 5.2 on 2026-03-03 23:24

import quiz.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_major_quiz_is_active_quiz_is_online_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_of_question',
            field=models.CharField(choices=[('تستی چهارگزینه\u200cای', 'تستی چهارگزینه\u200cای'), ('درست / نادرست', 'درست / نادرست'), ('پاسخ کوتاه', 'پاسخ کوتاه'), ('پاسخ تشریحی', 'پاسخ تشریحی'), ('مبتنی بر تصویر', 'مبتنی بر تصویر'), ('سوال از فایل PDF', 'سوال از فایل PDF')], max_length=100, verbose_name='نوع سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='filled_capacity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=' ظرفیت پر شده'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='student',
        ),
        migrations.AddField(
            model_name='quiz',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, related_name='quiz_student', to=settings.AUTH_USER_MODEL, verbose_name='دانش اموز'),
        ),
    ]
