# Generated by Django 5.2 on 2026-03-04 23:37

import django.db.models.deletion
import quiz.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_question_image_alter_question_pdf_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_return_to_questions',
            field=models.BooleanField(default=True, verbose_name='برگشتن به عقب'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='allow_to_edit_the_answered_questions',
            field=models.BooleanField(default=True, verbose_name='امکان ویرایش سوالات پاسخ داده شده'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='change_the_order',
            field=models.BooleanField(default=True, verbose_name=' عوض کردن ترتیب سوالات'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='is_skipped',
            field=models.BooleanField(default=False, verbose_name='رد شده'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrected_answers', to=settings.AUTH_USER_MODEL, verbose_name='تصحیح\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='quiz.question', verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.questionoption', verbose_name='گزینه انتخاب\u200cشده'),
        ),
    ]
