# Generated by Django 5.2 on 2026-03-05 00:20

import django.db.models.deletion
import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_allow_return_to_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='quiz.question', verbose_name='سوال'),
        ),
    ]
