# Generated by Django 5.2 on 2026-03-06 00:05

import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_question_options_alter_question_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='type_of_answer',
            field=models.CharField(blank=True, choices=[('پاسخ متنی', 'پاسخ متنی'), ('پاسخ تصویری', 'پاسخ تصویری'), ('پاسخ PDF', 'پاسخ PDF'), ('انتخاب گزینه', 'انتخاب گزینه'), ('رد شده', 'رد شده')], max_length=50, null=True, verbose_name='نوع پاسخ'),
        ),
    ]
