# Generated by Django 5.2 on 2026-03-07 16:37

import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_question_image_alter_question_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تمام شدن توسط کاربر'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='have_negetive_score',
            field=models.BooleanField(default=True, verbose_name='دارای نمره منفی'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ'),
        ),
    ]
