# Generated by Django 5.2 on 2026-03-09 13:24

import django_ckeditor_5.fields
import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_quiz_corrected_at_alter_question_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='corrected',
            field=models.CharField(blank=True, choices=[('کاملا اشتباه', 'کاملا اشتباه'), ('نیاز به تلاش بیشتر', 'نیاز به تلاش بیشتر'), ('قابل قبول', 'قابل قبول'), ('خوب', 'خوب'), ('عالی', 'عالی')], max_length=100, null=True, verbose_name='کیفیت جواب'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='satantorium_message',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='نظر مصصح'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ'),
        ),
    ]
