# Generated by Django 5.2 on 2026-03-09 17:55

import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_remove_studentanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='corrected',
            field=models.CharField(choices=[('تصحیح نشده', 'تصحیح نشده'), ('کاملا اشتباه', 'کاملا اشتباه'), ('نیاز به تلاش بیشتر', 'نیاز به تلاش بیشتر'), ('قابل قبول', 'قابل قبول'), ('نسبتا درست', 'نسبتا درست'), ('کاملا درست', 'کاملا درست')], default='تصحیح نشده', max_length=100, verbose_name='کیفیت جواب'),
        ),
    ]
