# Generated by Django 5.2 on 2026-03-09 23:18

import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_alter_question_image_alter_question_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'ordering': ['question__pk'], 'verbose_name': 'پاسخ دانش\u200cآموز', 'verbose_name_plural': 'پاسخ\u200cهای دانش\u200cآموزان'},
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_of_question',
            field=models.CharField(choices=[('تستی چهارگزینه\u200cای', 'تستی چهارگزینه\u200cای'), ('پاسخ کوتاه', 'پاسخ کوتاه'), ('پاسخ تشریحی', 'پاسخ تشریحی'), ('مبتنی بر تصویر', 'مبتنی بر تصویر'), ('سوال از فایل PDF', 'سوال از فایل PDF')], max_length=100, verbose_name='نوع سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تصحیح'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='type_of_answer',
            field=models.CharField(choices=[('انتخاب گزینه', 'انتخاب گزینه'), ('پاسخ متنی', 'پاسخ متنی'), ('پاسخ تصویری', 'پاسخ تصویری'), ('پاسخ PDF', 'پاسخ PDF'), ('رد شده', 'رد شده'), ('جواب داده نشده', 'جواب داده نشده')], default='جواب داده نشده', max_length=50, verbose_name='نوع پاسخ'),
        ),
    ]
