# Generated by Django 5.2 on 2026-03-10 16:53

import django.db.models.deletion
import quiz.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_alter_studentanswer_options_alter_question_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ'),
        ),
        migrations.CreateModel(
            name='UserQuizDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تمام شدن توسط کاربر')),
                ('out_of_page', models.PositiveSmallIntegerField(default=0, verbose_name='خروج از صفحه')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='نمره کل')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail', to='quiz.quiz', verbose_name='آزمون')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_detail', to=settings.AUTH_USER_MODEL, verbose_name='دانش اموز')),
            ],
            options={
                'verbose_name': 'جزییات ازمون برای دانش اموزان',
                'verbose_name_plural': 'جزییات ازمون ها برای دانش اموزان',
            },
        ),
    ]
