# Generated by Django 5.2 on 2026-03-14 19:11

import django.utils.timezone
import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_alter_question_image_alter_question_pdf_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='userquizdetail',
            name='finished_at',
        ),
        migrations.AddField(
            model_name='userquizdetail',
            name='student_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج کاربر از ازمون'),
        ),
        migrations.AddField(
            model_name='userquizdetail',
            name='student_start_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان ورود کاربر به ازمون'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ'),
        ),
    ]
