# Generated by Django 5.2 on 2026-03-19 21:01

import quiz.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_quiz_start_set_report_alter_question_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'ordering': ['student'], 'verbose_name': 'پاسخ دانش\u200cآموز', 'verbose_name_plural': 'پاسخ\u200cهای دانش\u200cآموزان'},
        ),
        migrations.RemoveField(
            model_name='userquizdetail',
            name='score',
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='عنوان سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='sanatorium',
            field=models.ManyToManyField(db_index=True, related_name='quiz_sanatorium', to=settings.AUTH_USER_MODEL, verbose_name='مصحح'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='student',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='quiz_student', to=settings.AUTH_USER_MODEL, verbose_name='دانش اموز'),
        ),
    ]
