# Generated by Django 5.2 on 2026-03-27 19:18

import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_alter_question_image_alter_question_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessioncategories',
            options={'ordering': ['-order'], 'verbose_name': 'درس ', 'verbose_name_plural': 'دروس'},
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(blank=True, choices=[('همه وضعیت ها ', 'همه وضعیت ها '), ('در انتظار شروع', 'در انتظار شروع'), ('شروع شده', 'شروع شده'), ('در انتظار پایان', 'در انتظار پایان'), ('پایان یافته', 'پایان یافته'), ('در انتظار تصحیح', 'در انتظار تصحیح'), ('تصحیح شده', 'تصحیح شده'), ('اعلام نتایج', 'اعلام نتایج'), ('غیرفعال', 'غیرفعال'), ('کنسل شده', 'کنسل شده')], default='در انتظار شروع', max_length=55, null=True, verbose_name='وضعیت'),
        ),
    ]
