# Generated by Django 5.2 on 2026-03-29 20:04

import django.db.models.deletion
import quiz.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0039_alter_lessioncategories_options_alter_question_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_of_question',
            field=models.CharField(choices=[('تستی چند گزینه\u200cای', 'تستی چند گزینه\u200cای'), ('پاسخ کوتاه', 'پاسخ کوتاه'), ('پاسخ تشریحی', 'پاسخ تشریحی'), ('مبتنی بر تصویر', 'مبتنی بر تصویر'), ('سوال از فایل PDF', 'سوال از فایل PDF')], max_length=100, verbose_name='نوع سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_answers', to=settings.AUTH_USER_MODEL, verbose_name='تصحیح\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.questionoption', verbose_name='گزینه انتخاب\u200cشده'),
        ),
    ]
