# Generated by Django 5.2 on 2026-04-03 19:46

import config.storage
import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0044_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.storage.PrivateMediaStorage, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=config.storage.PrivateMediaStorage, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.storage.PrivateMediaStorage, upload_to=quiz.models.photo_path_upload_to, verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=config.storage.PrivateMediaStorage, upload_to=quiz.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='allow_to_edit_the_question_after_the_user_finish',
            field=models.BooleanField(default=True, verbose_name='اجازه به ویرایش پاسخ بعد از اتمام کاربر و قبل از اتمام وقت'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='have_negetive_score',
            field=models.BooleanField(default=True, verbose_name='- '),
        ),
    ]
