# Generated by Django 5.2 on 2026-03-07 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0014_quiz_finished_at_quiz_have_negetive_score_and_more'),
        ('user', '0004_alter_user_private_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='نمره')),
                ('percent', models.PositiveIntegerField(verbose_name='درصد')),
                ('teraze', models.PositiveIntegerField(verbose_name='تراز')),
                ('order', models.PositiveIntegerField(verbose_name='رتبه')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='user.gradecategories', verbose_name='پایه')),
                ('lession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='quiz.lessioncategories', verbose_name='درس')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='user.majorcategories', verbose_name='رشته تحصیلی')),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='quiz.quiz', verbose_name='ازمون')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کارنامه ',
                'verbose_name_plural': 'کارنامه ها',
                'ordering': ['order'],
                'unique_together': {('quiz', 'user')},
            },
        ),
    ]
