# Generated by Django 5.2 on 2026-03-09 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_alter_studentanswer_options_alter_question_image_and_more'),
        ('report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('تصحیح نشده', 'تصحیح نشده'), ('نیاز به تلاش بیشتر', 'نیاز به تلاش بیشتر'), ('قابل قبول', 'متوسط'), ('نسبتا درست', 'خوب'), ('کاملا درست', 'عالی')], default='تصحیح نشده', max_length=100, verbose_name='وضعیت عملکردی'),
        ),
        migrations.AlterField(
            model_name='report',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='quiz.quiz', verbose_name='ازمون'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
