# Generated by Django 5.2 on 2026-03-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_status_alter_report_quiz_alter_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('تصحیح نشده', 'تصحیح نشده'), ('نیاز به تلاش بیشتر', 'نیاز به تلاش بیشتر'), ('متوسط', 'متوسط'), ('خوب', 'خوب'), ('عالی', 'عالی')], default='تصحیح نشده', max_length=100, verbose_name='وضعیت عملکردی'),
        ),
    ]
