# Generated by Django 5.2 on 2026-03-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='رتبه'),
        ),
        migrations.AlterField(
            model_name='report',
            name='teraze',
            field=models.PositiveIntegerField(default=0, verbose_name='تراز'),
        ),
    ]
