# Generated by Django 5.2 on 2026-04-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_report_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-order'], 'verbose_name': 'کارنامه ', 'verbose_name_plural': 'کارنامه ها'},
        ),
    ]
