# Generated by Django 5.2 on 2026-04-06 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_report_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-pk'], 'verbose_name': 'کارنامه ', 'verbose_name_plural': 'کارنامه ها'},
        ),
    ]
