# Generated by Django 5.2 on 2026-03-04 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_initial'),
        ('qbank', '0001_initial'),
        ('quiz', '0005_alter_question_image_alter_question_pdf_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ManyToManyField(related_name='favorate', to='blog.blog', verbose_name='مقاله')),
                ('qbank', models.ManyToManyField(related_name='favorate', to='qbank.questionbank', verbose_name='بانک سوال')),
                ('quiz', models.ManyToManyField(related_name='favorate', to='quiz.quiz', verbose_name='ازمون')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorate', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'علاقه مندی',
                'verbose_name_plural': 'علاقه مندی ها',
            },
        ),
    ]
