# Generated by Django 5.2 on 2026-03-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_sort_number_alter_blog_title_and_more'),
        ('dashboard', '0002_alter_userfavorate_user'),
        ('qbank', '0003_alter_questionanswerkey_options_and_more'),
        ('quiz', '0036_alter_studentanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorate',
            name='blog',
            field=models.ManyToManyField(db_index=True, related_name='favorate', to='blog.blog', verbose_name='مقاله'),
        ),
        migrations.AlterField(
            model_name='userfavorate',
            name='qbank',
            field=models.ManyToManyField(db_index=True, related_name='favorate', to='qbank.questionbank', verbose_name='بانک سوال'),
        ),
        migrations.AlterField(
            model_name='userfavorate',
            name='quiz',
            field=models.ManyToManyField(db_index=True, related_name='favorate', to='quiz.quiz', verbose_name='ازمون'),
        ),
    ]
