# Generated by Django 5.2 on 2026-03-03 22:18

import blog.models
import django_ckeditor_5.fields
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان انتشار')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('category', models.CharField(max_length=255, verbose_name='دسته')),
                ('short_content', models.CharField(max_length=100, verbose_name='توضیحات کوتاه')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='متن یا بدنه')),
                ('time_to_read_minutes', models.PositiveSmallIntegerField(default=10, verbose_name='زمان مطاعه بع دقیقه')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=blog.models.photo_path_upload_to, verbose_name='عکس')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال ')),
                ('sort_number', models.PositiveBigIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
