# Generated by Django 5.2 on 2026-02-28 00:06

import blog.models
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(max_length=255, verbose_name='دسته'),
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-sort_number'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(default=1, upload_to=blog.models.photo_path_upload_to, verbose_name='عکس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='short_content',
            field=models.CharField(default=1, max_length=100, verbose_name='توضیحات کوتاه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='time_to_read_minutes',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='زمان مطاعه بع دقیقه'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال / غیر فعال '),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sort_number',
            field=models.PositiveBigIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
