# Generated by Django 5.2 on 2026-03-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogview',
            options={'verbose_name': 'بازدید', 'verbose_name_plural': 'بازدیدها'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='time_to_read_minutes',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='زمان مطالعه به دقیقه'),
        ),
    ]
