# Generated by Django 5.2 on 2026-03-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sort_number',
            field=models.PositiveBigIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='blogview',
            name='count',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
