# Generated by Django 5.2 on 2026-04-03 15:00

import blog.models
import config.storage
import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(storage=config.storage.PublicMediaStorage, upload_to=blog.models.photo_path_upload_to, verbose_name='عکس'),
        ),
    ]
