"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v)jzbylc57v$uk247bwifv2nf@jvg%7n@3hpks^-g_u1%ws-8*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'sornac.ir' , 'sorna.runflare.run', '10.224.115.118']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third pary
    'django_ckeditor_5',
    'easy_thumbnails',
    'jalali_date',
    'storages',
    # 'corsheaders',

    # apps
    'user',
    'order',
    'dashboard',
    'quiz',
    'report',
    'sanatorium',
    'sitesetting',
    'admin_panel',
    'qbank',
    'blog',

]

CORS_ALLOW_ALL_ORIGINS = True

THUMBNAIL_DEFAULT_OPTIONS = {
    'format': 'WEBP',      # همیشه WebP تولید کنه
    'quality': 90,         # کیفیت پیش‌فرض (می‌تونی تغییر بدی)
    'crop': 'center',      # همیشه از مرکز crop کنه (اگر crop فعال باشه)
    'optimize': True,      # بهینه‌سازی lossless با Pillow
}


MIDDLEWARE = [
    # 'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'template'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


LANGUAGE_CODE = "fa"
USE_I18N = True
TIME_ZONE = "Asia/Tehran"
USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS=[
    BASE_DIR / 'static'
]


MEDIA_URL = '/media/'
MEDIA_ROOT =  BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# otp
OTP_EXPIRATIONS_SECONDS = 120
LOGIN_TEMP = 5

# user 
AUTH_USER_MODEL = 'user.User'
LOGIN_URL = "user:login"
LOGIN_REDIRECT_URL = "/"


# jalali date config
JALALI_DATE_DEFAULTS = {
    # if change it to true then all dates of the list_display will convert to the Jalali.
    "LIST_DISPLAY_AUTO_CONVERT": True,
    "Strftime": {
        "date": "%Y/%m/%d",
        "datetime": "%H:%M - %Y/%m/%d ",
    },
    "Static": {
        "js": [
            "admin/js/django_jalali.min.js",
        ],
        "css": {
            "all": [
                "admin/css/django_jalali.min.css",
            ]
        },
    },
}

# phone number config
PHONENUMBER_DEFAULT_FORMAT = "NATIONAL"
PHONENUMBER_DEFAULT_REGION = "IR"

# cke config
 

CKEDITOR_5_CONFIGS = {
'default': {
    'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],
    'language': 'fa',
},
}
 
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff"   
CKEDITOR_5_FILE_STORAGE = 'config.storage.CKEditorMediaStorage'

# object storage
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# اطلاعات اتصال
AWS_ACCESS_KEY_ID = 'ac023df1-eacb-4f6d-a2e7-27876110428f'
AWS_SECRET_ACCESS_KEY = '0fa8ff33ffb2badc391eee0362b8503778ad5100b48e50f90c0e906bfa219a2d'
AWS_STORAGE_BUCKET_NAME = 'sorna'
AWS_S3_REGION_NAME = 'ir-thr-at1'
 
AWS_S3_ENDPOINT_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.arvanstorage.ir'
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.arvanstorage.ir'
AWS_QUERYSTRING_EXPIRE = 1


FILE_UPLOAD_TEMP_DIR = BASE_DIR / 'tmp/'

# مدیریت آپلود فایل
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

DATA_UPLOAD_MAX_MEMORY_SIZE =  1024 * 1024 * 10
 

