# Generated by Django 5.2 on 2026-02-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateTimeField(null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='نام شهر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='father_name',
            field=models.CharField(max_length=255, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(max_length=255, null=True, verbose_name='پایه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(max_length=255, null=True, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(max_length=255, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(max_length=255, null=True, verbose_name='نام استان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(max_length=255, null=True, verbose_name='نام مدرسه'),
        ),
    ]
