# Generated by Django 5.2 on 2026-03-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_code',
            field=models.CharField(max_length=1000, null=True, verbose_name='نام پدر'),
        ),
    ]
