# Generated by Django 5.2 on 2026-03-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_private_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_temp',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='دفعات ورود'),
        ),
        migrations.AlterField(
            model_name='user',
            name='private_code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='نام پدر'),
        ),
    ]
