# Generated by Django 5.2 on 2026-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_login_temp_alter_user_private_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='private_code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='کد مخفی کاربر'),
        ),
    ]
