# Generated by Django 5.2 on 2026-03-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_private_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradecategories',
            options={'ordering': ['-order'], 'verbose_name': 'پایه', 'verbose_name_plural': 'پایه ها'},
        ),
        migrations.AlterModelOptions(
            name='majorcategories',
            options={'ordering': ['-order'], 'verbose_name': 'رشته ', 'verbose_name_plural': 'رشته ها'},
        ),
    ]
