# Generated by Django 5.2 on 2026-03-04 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0007_quiz_allow_return_to_questions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('status', models.CharField(choices=[('فعال', 'فعال'), ('کنسل شده', 'کنسل شده'), ('پرداخت شده', 'پرداخت شده')], default='فعال', verbose_name='وضعیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail', to='order.order')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'جزییات سفارش',
                'verbose_name_plural': 'جزییات سفارشات',
            },
        ),
    ]
