# Generated by Django 5.2 on 2026-03-08 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('quiz', '0019_alter_question_image_alter_question_pdf_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد های خرید'},
        ),
        migrations.AddField(
            model_name='order',
            name='ZarinPal_fee',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینه اخذ شده توسط درگاه پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='authority',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='کد درگاه پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='کارت'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart_hash',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='کارت هش شده'),
        ),
        migrations.AddField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.PositiveBigIntegerField(default=0, verbose_name='کد پیگیری'),
        ),
        migrations.AddField(
            model_name='order',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('فعال', 'فعال'), ('کنسل شده', 'کنسل شده'), ('کنسل شده توسط ادمین', 'کنسل شده توسط ادمین'), ('پرداخت شده', 'پرداخت شده')], default='فعال', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='order.order', verbose_name='سبد خرید'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='quiz.quiz', verbose_name='ازمون'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مبلغ تخفیف (اختیاری)')),
                ('percent', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='درصد تخفیف (اختیاری)')),
                ('min_price', models.PositiveBigIntegerField(default=0, verbose_name='حداقل قیمت جهت اعمال تخفیف')),
                ('end_date_discount', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('start_date_discount', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('count', models.PositiveBigIntegerField(default=0, verbose_name='تعداد')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='نام')),
                ('count_of_use_per_user', models.PositiveIntegerField(default=1, verbose_name='اجازه استفاده برای هر کاربر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
                ('order', models.ManyToManyField(related_name='discounts', to='order.order', verbose_name='سبد های خرید')),
                ('quiz', models.ManyToManyField(related_name='discounts', to='quiz.quiz', verbose_name='ازمون ها')),
                ('user', models.ManyToManyField(related_name='discounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کد تخفیف ',
                'verbose_name_plural': 'کد تخفیف ها',
            },
        ),
    ]
