# Generated by Django 5.2 on 2026-03-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_order_zarinpal_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال بودن'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال بودن'),
        ),
    ]
