# Generated by Django 5.2 on 2026-03-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_is_active_orderdetail_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('جاری', 'جاری'), ('کنسل شده', 'کنسل شده'), ('کنسل شده توسط ادمین', 'کنسل شده توسط ادمین'), ('پرداخت شده', 'پرداخت شده')], default='جاری', verbose_name='وضعیت'),
        ),
    ]
